### ISSUE TITLE
Light, dark and system theme toggles

### ISSUE THREAD

**Issue by iamscotttaylor** [TryGhost/Dawn#6]
I've successfully changed the styling of blockquotes for both light and dark mode. But where I've found a potential bug (or perhaps just my lack of knowledge) is with "System Theme" at night time. It shows the a mix of styles for both the light and dark mode.

```
.theme-dark blockquote {
  background-color: #353b4a;
  color: #ffffff;
}
```

**Comment by minimaluminium** [comment]
Hey Scott, do you have any live example where I can reproduce the issue?

**Comment by iamscotttaylor** [comment]
Hey — yep st (dot) im. 

If you put your system into dark mode then view "system theme" — you'll be able to see what I'm talking about.

Thanks so much.

**Comment by minimaluminium** [comment]
Thanks, that really helps. I see the issue now. You actually need 2 pieces of CSS to make it work on both client and system theme. The first part is for client theme (Dark) and the latter one is for system theme (System).

When you select a client theme (light or dark), the theme toggles `theme-light` and `theme-dark` classes accordingly. When system theme is selected, the classes are cleared and `prefers-color-scheme` media query is required.

Nice domain btw :)

```css
.theme-dark blockquote {
    background-color: #353b4a;
    color: #fff;
}

@media (prefers-color-scheme: dark) {
    html:not(.theme-light) blockquote {
        background-color: #353b4a;
        color: #fff;
    }
}
```
